<a href="https://colab.research.google.com/github/abdullah1234-bit/NLP-/blob/main/BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [7]:
X_train.shape

(4457,)

In [8]:
X_test.shape

(1115,)

In [9]:
X_train[:4]

4768    Your unique user ID is 1172. For removal send ...
3203    Okay lor... Wah... like that def they wont let...
1407    URGENT, IMPORTANT INFORMATION FOR O2 USER. TOD...
3963    You have been specially selected to receive a ...
Name: Message, dtype: object

In [10]:
y_train[:4]

4768    1
3203    0
1407    1
3963    1
Name: spam, dtype: int64

# **Create bag of words representation using CountVectorizer**

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7767 sparse matrix of type '<class 'numpy.int64'>'
	with 59641 stored elements in Compressed Sparse Row format>

In [12]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
X_train_cv.shape

(4457, 7767)

In [16]:
v.get_feature_names_out()[7736]

'your'

In [15]:
v.vocabulary_

{'your': 7736,
 'unique': 7182,
 'user': 7245,
 'id': 3605,
 'is': 3769,
 '1172': 270,
 'for': 2956,
 'removal': 5722,
 'send': 6040,
 'stop': 6530,
 'to': 6961,
 '87239': 686,
 'customer': 2135,
 'services': 6060,
 '08708034412': 90,
 'okay': 4944,
 'lor': 4222,
 'wah': 7369,
 'like': 4135,
 'that': 6839,
 'def': 2228,
 'they': 6866,
 'wont': 7605,
 'let': 4110,
 'us': 7237,
 'go': 3171,
 'haha': 3305,
 'what': 7494,
 'did': 2307,
 'say': 5952,
 'in': 3661,
 'the': 6842,
 'terms': 6802,
 'and': 951,
 'conditions': 1960,
 'urgent': 7227,
 'important': 3650,
 'information': 3694,
 'o2': 4902,
 'today': 6966,
 'lucky': 4270,
 'day': 2188,
 'find': 2871,
 'out': 5034,
 'why': 7524,
 'log': 4197,
 'onto': 4974,
 'http': 3551,
 'www': 7666,
 'urawinner': 7224,
 'com': 1910,
 'there': 6859,
 'fantastic': 2788,
 'surprise': 6661,
 'awaiting': 1166,
 'you': 7734,
 'have': 3371,
 'been': 1293,
 'specially': 6401,
 'selected': 6026,
 'receive': 5650,
 '3000': 413,
 'award': 1168,
 'call': 1612,


In [17]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [18]:
np.where(X_train_np[0]!=0)

(array([  90,  270,  686, 2135, 2956, 3605, 3769, 5722, 6040, 6060, 6530,
        6961, 7182, 7245, 7736]),)

# Train the naive bayes model

In [19]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [20]:
X_test_cv = v.transform(X_test)

# Evaluate Performance

In [21]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       970
           1       0.98      0.91      0.94       145

    accuracy                           0.99      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [23]:
emails = [
    'Ok lor... Or u wan me go look 4 u?',
    'you win $50000 if you click this link'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

# Train the model using sklearn pipeline and reduce number of lines of code

In [24]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [25]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       970
           1       0.98      0.91      0.94       145

    accuracy                           0.99      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [27]:
emails = [
    'Ok lor... Or u wan me go look 4 u?',
    'you win $50000 if you click this link'
]

# Predict using the pipeline
predictions = clf.predict(emails)

# Print the results
print(predictions)

[0 1]
